### ISSUE TITLE
Cannot load US ACE inland rivers

### ISSUE THREAD

**Issue by transmitterdan** [nohal/chartdldr_pi#13] opened 2015-01-20 23:38 UTC
(NOTE: These comments contain XML so you may have to "edit" the comment to see the actual XML text.)

When trying to populate the list of charts for ACE inland rivers this function:

bool ChartCatalog::LoadFromFile(wxString path, bool headerOnly)

returns false when reading the file "iencu37productscatalog.xml". When reading other NOAA xml files it works. For some reason this line ret = LoadFromXml(doc, headerOnly); returns false when reading that file. The first part of "iencu37productscatalog.xml" looks like this:

<?xml version="1.0" encoding="UTF-8"?>

<IENCU37ProductCatalog>

<Header>

<title>IENC U37 Product Catalog</title>

<date_created>01/14/2015</date_created>

<time_created>14:33:32</time_created>

<ref_spec>USACE IENC Product Catalog Technical Specifications</ref_spec>

<ref_spec_vers>1</ref_spec_vers>

</Header>

I am not sure why the LoadFromXml() call fails.

This is the first part from another file that will return true:

<RncProductCatalog17Region>
<Header><title>RNC Product Catalog 17 Region</title><date_created>2015-01-16</date_created><time_created>08:42:00</time_created><date_valid>2015-01-16</date_valid><time_valid>08:42:00</time_valid><dt_valid>2015-01-16T13:42:00Z</dt_valid><ref_spec>NOAA Rnc Product Catalog 17 Region Technical Specifications</ref_spec><ref_spec_vers>1.0</ref_spec_vers><s62AgencyCode>550</s62AgencyCode></Header>

The net result is that because the inland rivers catalog file cannot be loaded the list of charts does not populate.

**Comment by nohal** [comment] 2015-01-20 23:43
Duplicate of #3

**Closed as completed** 2015-01-21 03:30 UTC
