### ISSUE TITLE
 smaller window hides buttons (#22 did NOT fix)

### ISSUE THREAD

**Issue by LeaseOnLife** [nohal/chartdldr_pi#27] opened 2015-01-25 20:37 UTC
after #22 the "download selected charts" button is now visible but the four buttons to th right "Add", "Delete", "Edit", "Update" are still hidden. see screenshot.
![chartdownloader-004](https://cloud.githubusercontent.com/assets/919044/5893176/124bbe88-a4a8-11e4-8391-ffa5fabc7375.jpg)

**Comment by nohal** [comment] 2015-01-25 20:46
Does it look like this immediately after accessing the Toolbox tab?
When you resize the Toolbox, does the panel adjust properly?
I can't reproduce it on Gnome Shell and Windows, but see something perhaps similar on OS X - until a sizing event comes from the Toolbox window, the chartdldr panel is "too small"...
If it is the case, try putting `m_dldrpanel->Layout();` (or something similar forcing the recalculation) on line 223 in chartdldr_pi.cpp.

**Comment by LeaseOnLife** [comment] 2015-01-25 20:55
- yes it does look like this immediately after accessing the Toolbox tab
- When you resize the Toolbox, does the panel adjust properly? No!
- If it is the case, try putting m_dldrpanel->Layout(); (or something similar forcing the recalculation) on line 223 in chartdldr_pi.cpp. ==> I tried that, ...make install, restarted opencpn, no change. 
- The buttons only appear when resizing the window beyond a certain size. Attached screenshot illustrates this, showing half buttons after a resize.

![chartdownloader-005](https://cloud.githubusercontent.com/assets/919044/5893250/6f818ac2-a4aa-11e4-9b87-ff2e72e2e418.jpg)

**Comment by LeaseOnLife** [comment] 2015-01-25 20:57
BTW, I am using KDE here, no OS-X around here

**Comment by nohal** [comment] 2015-01-25 21:38
I know, but the issue is most likely the same or very similar

**Comment by nohal** [comment] 2015-01-25 22:14
The issue on Mac is fixed in https://github.com/nohal/chartdldr_pi/commit/f7893baa5f957f9d1ce659ebb7e877b25be8b078, does it have any impact on the initial sizing on KDE?
I suspect that the list control on KDE refuses to shrink bellow the cumulative width of it's columns, so we will probably have to help them with shrinking somehow...

**Comment by LeaseOnLife** [comment] 2015-01-25 22:30
Yup KDE seems stubborn, did a git reset --hard, git pull and make install, restart opencpn, still same behaviour.

I tested your theory and the Tab "Chart files" shows a similar behavior when shrinking the window to be smaller than my (long) path names, the buttons "Add Directory" and "Remove Selected" also get cut off, then disppear. So this is more of a generic bug, not just a plug-in bug.

**Comment by nohal** [comment] 2015-01-25 22:40
I'm afraid it is a KDE feature... Not sure I can do more than force the columns to be narrower...
If you change the preset column widths in chartdldr_pi.cpp, lines 61-66, does it have some effect, or does KDE still make the list too wide?

**Comment by LeaseOnLife** [comment] 2015-01-25 22:48
yes, that works, I reduced them to an extreme (like one-tenth of the original value), but yes, KDE follows that.

**Comment by LeaseOnLife** [comment] 2015-01-25 22:57
This looks OK on this machine:
#else
#define CATALOGS_NAME_WIDTH 200
#define CATALOGS_DATE_WIDTH 120
#define CATALOGS_PATH_WIDTH 250
#define CHARTS_NAME_WIDTH 200
#define CHARTS_STATUS_WIDTH 150
#define CHARTS_DATE_WIDTH 150
#endif // **WXMAC**

![chartdownloader-006](https://cloud.githubusercontent.com/assets/919044/5893679/90fa4674-a4bb-11e4-9cb0-090737d9091f.jpg)

**Comment by nohal** [comment] 2015-01-25 23:12
Thanks...
Can you try

```
#define CATALOGS_NAME_WIDTH 200
#define CATALOGS_DATE_WIDTH 130
#define CATALOGS_PATH_WIDTH 250
#define CHARTS_NAME_WIDTH 320
#define CHARTS_STATUS_WIDTH 150
#define CHARTS_DATE_WIDTH 130
```

I would like to settle on the best compromise...
My machine needs CATALOGS_DATE_WIDTH 10 pixels wider to show enough of the date (if it is a problem, I would prefer stealing those 10 from path)
And it seems your values for the chart list are a bit too conservative, given there is more estate available, I suppose the total width can be more than the catalog list on the top - Unless there is something KDE does and I don't understand yet...

**Comment by LeaseOnLife** [comment] 2015-01-25 23:17
Your values look good here!

![chartdownloader-007](https://cloud.githubusercontent.com/assets/919044/5893756/5c5d7f32-a4be-11e4-815b-89f2cb8942f3.jpg)

**Closed as completed** 2015-01-25 23:20 UTC
Labels: bug
